### ISSUE TITLE
Cache expire patterns

### ISSUE THREAD

**Issue by sidinwillis** [BackendStack21/http-cache-middleware#13]
Hi, thank you for sharing!

I think there's a paranthesis here put in the wrong place:

```javascript
const patterns = keysPattern.split(',').map(
     pattern => pattern.endsWith('*') ? pattern : [pattern, pattern + DATA_POSTFIX]) //<--here
    .reduce((acc, item) =>
    {           
        acc.push(...item)
        return acc          
    }, [])
```

If the pattern is

`*/test*`

the _reduce_ would make this an array of char.

The first character (*) is then passed to getkeys, deleting the entire database.

I fixed it in this way

```javascript
const patterns = keysPattern.split(',').map(
     pattern => pattern.endsWith('*') ? pattern : [pattern, pattern + DATA_POSTFIX]
    .reduce((acc, item) =>
    {           
        acc.push(...item)
        return acc          
    }, [])) <--here
```

I wrong something?

**Comment by jkyberneees** [comment]
Hi @sidinwillis thanks for reporting. 
I have pushed the fix up, could you please review and comment before merging?

Regards

**Comment by sidinwillis** [comment]
Thanks to you!

Great, actually _patterns_ is an array so your solution works fine. 

I've tested in local env and work well.
